version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    tty: true
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    networks:
      - app-network

  backend:
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:8000 Liber.wsgi:application
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DEBUG: 0

    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge
